apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: wes-gateway
build:
  local:
    useDockerCLI: true
  artifacts:
    - image: dev.local/eoepca/wes-gateway
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: wes-gateway
        chartPath: charts/wes-gateway
        namespace: wes-gateway
        createNamespace: true
        setFiles:
          backendConfig: config/backends.yaml
        setValueTemplates:
          image.ref: "{{.IMAGE_FULLY_QUALIFIED_dev_local_eoepca_wes_gateway}}"
        wait: true
portForward:
  - resourceType: service
    resourceName: wes-gateway
    namespace: wes-gateway
    port: 8090
    localPort: 8090
