version: '3'

includes:
  openapi: https://raw.githubusercontent.com/Terradue/taskfile-utils/refs/heads/main/openapi.yaml

tasks:

  download_openapi:
    internal: true
    status:
    - '[ -f schemas/openapi.json ]'
    cmds:
    - mkdir -p schemas
    - |
      wget -O schemas/openapi.json \
      https://ga4gh.github.io/workflow-execution-service-schemas/openapi.json 

  generate_docs:
    deps:
    - download_openapi
    cmds:
    - task: openapi:generate_docs
      vars:
        API: 'schemas/openapi.json'
        OUTPUT: 'docs/c4/components/OpenAPI/apidoc.html'

  generate_skeleton:
    deps:
    - download_openapi
    cmds:
    - task: openapi:generate_skeleton
      vars:
        API: 'schemas/openapi.json'
        OUTPUT: './src/wes_api_gateway'

  default:
    cmds:
    - task: generate_docs
    - task: generate_skeleton
