# Copyright 2026 EOEPCA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-06T10:35:10+00:00

from __future__ import annotations

from .models import (
    ErrorResponse,
    RunId,
    RunListResponse,
    RunLog,
    RunStatus,
    ServiceInfo,
    TaskListResponse,
    TaskLog,
)
from fastapi import FastAPI, HTTPException, UploadFile
from http import HTTPStatus
from typing import List, Optional, Union

app = FastAPI(
    title="Workflow Execution Service",
    contact={},
    version="1.1.0",
    description="*Run standard workflows on workflow execution platforms in a platform-agnostic way.*\n## Executive Summary\nThe Workflow Execution Service (WES) API provides a standard way for users to submit workflow requests to workflow execution systems, and to monitor their execution. This API lets users run a single workflow (currently [**CWL**](https://www.commonwl.org/) or [**WDL**](http://www.openwdl.org/) formatted workflows, other types may be supported in the future) on multiple different platforms, clouds, and environments.\nKey features of the API:\n+ can request that a workflow be run + can pass parameters to that workflow (e.g. input files, cmdline arguments) + can get information about running workflows (e.g. status, errors, output file locations) + can cancel a running workflow\n",
    servers=[
        {
            "url": "https://{defaultHost}/{basePath}/{apiVersion}",
            "variables": {
                "defaultHost": {"default": "www.example.com"},
                "basePath": {"default": "ga4gh/wes"},
                "apiVersion": {"default": "v1"},
            },
        }
    ],
)


@app.get(
    "/runs",
    response_model=RunListResponse,
    responses={
        "400": {"model": ErrorResponse},
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def list_runs(
    page_size: Optional[int] = None, page_token: Optional[str] = None
) -> Union[RunListResponse, ErrorResponse]:
    """
    ListRuns
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.post(
    "/runs",
    response_model=RunId,
    responses={
        "400": {"model": ErrorResponse},
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def run_workflow(workflow_attachment: List[UploadFile]) -> Union[RunId, ErrorResponse]:
    """
    RunWorkflow
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.get(
    "/runs/{run_id}",
    response_model=RunLog,
    responses={
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "404": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def get_run_log(run_id: str) -> Union[RunLog, ErrorResponse]:
    """
    GetRunLog
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.post(
    "/runs/{run_id}/cancel",
    response_model=RunId,
    responses={
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "404": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def cancel_run(run_id: str) -> Union[RunId, ErrorResponse]:
    """
    CancelRun
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.get(
    "/runs/{run_id}/status",
    response_model=RunStatus,
    responses={
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "404": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def get_run_status(run_id: str) -> Union[RunStatus, ErrorResponse]:
    """
    GetRunStatus
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.get(
    "/runs/{run_id}/tasks",
    response_model=TaskListResponse,
    responses={
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "404": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def list_tasks(
    run_id: str, page_size: Optional[int] = None, page_token: Optional[str] = None
) -> Union[TaskListResponse, ErrorResponse]:
    """
    ListTasks
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.get(
    "/runs/{run_id}/tasks/{task_id}",
    response_model=TaskLog,
    responses={
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "404": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Workflow Runs"],
)
def get_task(run_id: str, task_id: str = ...) -> Union[TaskLog, ErrorResponse]:
    """
    GetTask
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)


@app.get(
    "/service-info",
    response_model=ServiceInfo,
    responses={
        "400": {"model": ErrorResponse},
        "401": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["Service Info"],
)
def get_service_info() -> Union[ServiceInfo, ErrorResponse]:
    """
    GetServiceInfo
    """
    # for now, return not implemented
    raise HTTPException(status_code=HTTPStatus.NOT_IMPLEMENTED.value)
