{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wes-gateway.serviceAccount" . }}
  labels:
    {{- include "wes-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
